In [1]:
import sys
print("Python:", sys.version)

import pathlib, os
data_dir = pathlib.Path("../Dataset/Raw")
csvs = sorted([p for p in data_dir.glob("**/*.csv")])
print(f"Found {len(csvs)} CSV files under {data_dir.resolve()}")
for p in csvs:
    print("-", p.relative_to(data_dir), f"({p.stat().st_size//1024} KB)")

import pandas as pd
sample_files = csvs[:6]
for p in sample_files:
    print("\n--", p.name)
    try:
        df = pd.read_csv(p, nrows=5)
        print(df.columns.tolist())
        display(df.head(3))
    except Exception as e:
        print("Could not read:", e)

Python: 3.13.4 (tags/v3.13.4:8a526ec, Jun  3 2025, 17:46:04) [MSC v.1943 64 bit (AMD64)]
Found 16 CSV files under C:\CSIE\My Projects\Data_Science\BoardGames_Analyzer\Dataset\Raw
- 2020-08-19.csv (3599 KB)
- 2022-01-08.csv (4936 KB)
- artists_reduced.csv (72120 KB)
- designers_reduced.csv (68393 KB)
- games.csv (21622 KB)
- games_detailed_info.csv (97135 KB)
- large_bgg-15m-reviews.csv (1358299 KB)
- large_bgg-19m-reviews.csv (1586828 KB)
- large_bgg-26m-reviews.csv (2128129 KB)
- large_games_detailed_info2025.csv (107483 KB)
- large_user_ratings.csv (390035 KB)
- mechanics.csv (6880 KB)
- publishers_reduced.csv (80047 KB)
- ratings_distribution.csv (8487 KB)
- subcategories.csv (583 KB)
- themes.csv (9451 KB)

-- 2020-08-19.csv
['Unnamed: 0', 'ID', 'Name', 'Year', 'Rank', 'Average', 'Bayes average', 'Users rated', 'URL', 'Thumbnail']

,Unnamed: 0,ID,Name,Year,Rank,Average,Bayes average,Users rated,URL,Thumbnail
0,90,30549,Pandemic,2008,91,7.62,7.518,96186,/boardgame/30549/pandemic,https://cf.geekdo-images.com/micro/img/0m3-oqB...
1,172,822,Carcassonne,2000,173,7.42,7.311,96181,/boardgame/822/carcassonne,https://cf.geekdo-images.com/micro/img/z0tTaij...
2,380,13,Catan,1995,381,7.16,7.001,96171,/boardgame/13/catan,https://cf.geekdo-images.com/micro/img/e0y6Bog...

-- 2022-01-08.csv
['Unnamed: 0', 'ID', 'Name', 'Year', 'Rank', 'Average', 'Bayes average', 'Users rated', 'URL', 'Thumbnail']

,Unnamed: 0,ID,Name,Year,Rank,Average,Bayes average,Users rated,URL,Thumbnail
0,105,30549,Pandemic,2008,106,7.59,7.487,108975,/boardgame/30549/pandemic,https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXL...
1,189,822,Carcassonne,2000,190,7.42,7.309,108738,/boardgame/822/carcassonne,https://cf.geekdo-images.com/okM0dq_bEXnbyQTOv...
2,428,13,Catan,1995,429,7.14,6.970,108024,/boardgame/13/catan,https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ...

-- artists_reduced.csv

,Harald Lieske,Franz Vohwinkel,Peter Whitley,Scott Okumura,(Uncredited),Doris Matthäus,Alan R. Moon,Alexander Jung,Andrea Boekhoff,Björn Pertoft,...,Nathan Meunier,Andrey Gordeev,Zbigniew Umgelter,Jeppe Norsker,Daniel Profiri,Aleksander Zawada,Simon Douchy,Felix Wermke,BGGId,Low-Exp Artist
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,1
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3,0

-- designers_reduced.csv

,Karl-Heinz Schmiel,"G. W. ""Jerry"" D'Arcey",Reiner Knizia,Sid Sackson,Jean du Poël,Martin Wallace,Richard Ulrich,Wolfgang Kramer,Alan R. Moon,Uwe Rosenberg,...,Thomas Dupont,Mathieu Casnin,Sean Fletcher,Moritz Dressler,Molly Johnson,Robert Melvin,Shawn Stankewich,Nathan Meunier,BGGId,Low-Exp Designer
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3,0

-- games.csv
['BGGId', 'Name', 'Description', 'YearPublished', 'GameWeight', 'AvgRating', 'BayesAvgRating', 'StdDev', 'MinPlayers', 'MaxPlayers', 'ComAgeRec', 'LanguageEase', 'BestPlayers', 'GoodPlayers', 'NumOwned', 'NumWant', 'NumWish', 'NumWeightVotes', 'MfgPlaytime', 'ComMinPlaytime', 'ComMaxPlaytime', 'MfgAgeRec', 'NumUserRatings', 'NumComments', 'NumAlternates', 'NumExpansions', 'NumImplementations', 'IsReimplementation', 'Family', 'Kickstarted', 'ImagePath', 'Rank:boardgame', 'Rank:strategygames', 'Rank:abstracts', 'Rank:familygames', 'Rank:thematic', 'Rank:cgs', 'Rank:wargames', 'Rank:partygames', 'Rank:childrensgames', 'Cat:Thematic', 'Cat:Strategy', 'Cat:War', 'Cat:Family', 'Cat:CGS', 'Cat:Abstract', 'Cat:Party', 'Cat:Childrens']

,BGGId,Name,Description,YearPublished,GameWeight,AvgRating,BayesAvgRating,StdDev,MinPlayers,MaxPlayers,...,Rank:partygames,Rank:childrensgames,Cat:Thematic,Cat:Strategy,Cat:War,Cat:Family,Cat:CGS,Cat:Abstract,Cat:Party,Cat:Childrens
0,1,Die Macher,die macher game seven sequential political rac...,1986,4.3206,7.61428,7.10363,1.57979,3,5,...,21926,21926,0,1,0,0,0,0,0,0
1,2,Dragonmaster,dragonmaster tricktaking card game base old ga...,1981,1.9630,6.64537,5.78447,1.45440,3,4,...,21926,21926,0,1,0,0,0,0,0,0
2,3,Samurai,samurai set medieval japan player compete gain...,1998,2.4859,7.45601,7.23994,1.18227,2,4,...,21926,21926,0,1,0,0,0,0,0,0

-- games_detailed_info.csv
['Unnamed: 0', 'type', 'id', 'thumbnail', 'image', 'primary', 'alternate', 'description', 'yearpublished', 'minplayers', 'maxplayers', 'suggested_num_players', 'suggested_playerage', 'suggested_language_dependence', 'playingtime', 'minplaytime', 'maxplaytime', 'minage', 'boardgamecategory', 'boardgamemechanic', 'boardgamefamily', 'boardgameexpansion', 'boardgameimplementation', 'boardgamedesigner', 'boardgameartist', 'boardgamepublisher', 'usersrated', 'average', 'bayesaverage', 'Board Game Rank', 'Strategy Game Rank', 'Family Game Rank', 'stddev', 'median', 'owned', 'trading', 'wanting', 'wishing', 'numcomments', 'numweights', 'averageweight', 'boardgameintegration', 'boardgamecompilation', 'Party Game Rank', 'Abstract Game Rank', 'Thematic Rank', 'War Game Rank', 'Customizable Rank', "Children's Game Rank", 'RPG Item Rank', 'Accessory Rank', 'Video Game Rank', 'Amiga Rank', 'Commodore 64 Rank', 'Arcade Rank', 'Atari ST Rank']

,Unnamed: 0,type,id,thumbnail,image,primary,alternate,description,yearpublished,minplayers,...,War Game Rank,Customizable Rank,Children's Game Rank,RPG Item Rank,Accessory Rank,Video Game Rank,Amiga Rank,Commodore 64 Rank,Arcade Rank,Atari ST Rank
0,0,boardgame,30549,https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXL...,https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXL...,Pandemic,"['EPIZOotic', 'Pandemia', 'Pandemia 10 Anivers...","In Pandemic, several virulent diseases have br...",2008,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,boardgame,822,https://cf.geekdo-images.com/okM0dq_bEXnbyQTOv...,https://cf.geekdo-images.com/okM0dq_bEXnbyQTOv...,Carcassonne,"['Carcassonne Jubilee Edition', 'Carcassonne: ...",Carcassonne is a tile-placement game in which ...,2000,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,boardgame,13,https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ...,https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ...,Catan,"['CATAN', 'Catan (Колонизаторы)', 'Catan telep...","In CATAN (formerly The Settlers of Catan), pla...",1995,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
import pandas as pd

files = [
    "large_bgg-26m-reviews.csv",
    "large_games_detailed_info2025.csv",
    "games.csv",
    "games_detailed_info.csv",
    "mechanics.csv",
    "themes.csv",
    "subcategories.csv"
]

for f in files:
    print("\n=== Preview:", f, "===")
    path = f"../Dataset/Raw/{f}"
    try:
        df = pd.read_csv(path, nrows=5)
        print(df.columns.tolist())
        display(df.head(3))
    except Exception as e:
        print("Error reading", f, ":", e)

=== Preview: large_bgg-26m-reviews.csv ===
['Unnamed: 0', 'user', 'rating', 'comment', 'ID', 'name']

,Unnamed: 0,user,rating,comment,ID,name
0,0,sidehacker,10.0,NaN,13,CATAN
1,1,Varthlokkur,10.0,NaN,13,CATAN
2,2,dougthonus,10.0,"Currently, this sits on my list as my favorite...",13,CATAN

=== Preview: large_games_detailed_info2025.csv ===
['Unnamed: 0', 'type', 'id', 'thumbnail', 'image', 'alternate', 'description', 'yearpublished', 'minplayers', 'maxplayers', 'suggested_num_players', 'suggested_playerage', 'suggested_language_dependence', 'playingtime', 'minplaytime', 'maxplaytime', 'minage', 'boardgamecategory', 'boardgamemechanic', 'boardgamefamily', 'boardgameexpansion', 'boardgameaccessory', 'boardgamecompilation', 'boardgameimplementation', 'boardgamedesigner', 'boardgameartist', 'boardgamepublisher', 'usersrated', 'average', 'bayesaverage', 'Board Game Rank', 'Strategy Game Rank', 'Family Game Rank', 'stddev', 'median', 'owned', 'trading', 'wanting', 'wishing', 'numcomments', 'numweights', 'averageweight', 'boardgameintegration', 'Abstract Game Rank', 'Party Game Rank', 'Thematic Rank', 'War Game Rank', 'Customizable Rank', "Children's Game Rank", 'RPG Item Rank', 'Accessory Rank', 'name']

,Unnamed: 0,type,id,thumbnail,image,alternate,description,yearpublished,minplayers,maxplayers,...,boardgameintegration,Abstract Game Rank,Party Game Rank,Thematic Rank,War Game Rank,Customizable Rank,Children's Game Rank,RPG Item Rank,Accessory Rank,name
0,0,boardgame,13,https://cf.geekdo-images.com/PyUol9QxBnZQCJqZI...,https://cf.geekdo-images.com/PyUol9QxBnZQCJqZI...,"['Catan', 'Catan (Колонизаторы)', 'Catan telep...","In CATAN (formerly The Settlers of Catan), pla...",1995,3,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CATAN
1,1,boardgame,822,https://cf.geekdo-images.com/okM0dq_bEXnbyQTOv...,https://cf.geekdo-images.com/okM0dq_bEXnbyQTOv...,"['Carcassonne Jubilee Edition', 'Carcassonne: ...",Carcassonne is a tile placement game in which ...,2000,2,5,...,"['Carcassonne: Wheel of Fortune', 'Mists over ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carcassonne
2,2,boardgame,30549,https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXL...,https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXL...,"['EPIZOotic', 'Pandemia', 'Pandemia 10 Anivers...","In Pandemic, several virulent diseases have br...",2008,2,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pandemic

=== Preview: games.csv ===
['BGGId', 'Name', 'Description', 'YearPublished', 'GameWeight', 'AvgRating', 'BayesAvgRating', 'StdDev', 'MinPlayers', 'MaxPlayers', 'ComAgeRec', 'LanguageEase', 'BestPlayers', 'GoodPlayers', 'NumOwned', 'NumWant', 'NumWish', 'NumWeightVotes', 'MfgPlaytime', 'ComMinPlaytime', 'ComMaxPlaytime', 'MfgAgeRec', 'NumUserRatings', 'NumComments', 'NumAlternates', 'NumExpansions', 'NumImplementations', 'IsReimplementation', 'Family', 'Kickstarted', 'ImagePath', 'Rank:boardgame', 'Rank:strategygames', 'Rank:abstracts', 'Rank:familygames', 'Rank:thematic', 'Rank:cgs', 'Rank:wargames', 'Rank:partygames', 'Rank:childrensgames', 'Cat:Thematic', 'Cat:Strategy', 'Cat:War', 'Cat:Family', 'Cat:CGS', 'Cat:Abstract', 'Cat:Party', 'Cat:Childrens']

,BGGId,Name,Description,YearPublished,GameWeight,AvgRating,BayesAvgRating,StdDev,MinPlayers,MaxPlayers,...,Rank:partygames,Rank:childrensgames,Cat:Thematic,Cat:Strategy,Cat:War,Cat:Family,Cat:CGS,Cat:Abstract,Cat:Party,Cat:Childrens
0,1,Die Macher,die macher game seven sequential political rac...,1986,4.3206,7.61428,7.10363,1.57979,3,5,...,21926,21926,0,1,0,0,0,0,0,0
1,2,Dragonmaster,dragonmaster tricktaking card game base old ga...,1981,1.9630,6.64537,5.78447,1.45440,3,4,...,21926,21926,0,1,0,0,0,0,0,0
2,3,Samurai,samurai set medieval japan player compete gain...,1998,2.4859,7.45601,7.23994,1.18227,2,4,...,21926,21926,0,1,0,0,0,0,0,0

=== Preview: games_detailed_info.csv ===
['Unnamed: 0', 'type', 'id', 'thumbnail', 'image', 'primary', 'alternate', 'description', 'yearpublished', 'minplayers', 'maxplayers', 'suggested_num_players', 'suggested_playerage', 'suggested_language_dependence', 'playingtime', 'minplaytime', 'maxplaytime', 'minage', 'boardgamecategory', 'boardgamemechanic', 'boardgamefamily', 'boardgameexpansion', 'boardgameimplementation', 'boardgamedesigner', 'boardgameartist', 'boardgamepublisher', 'usersrated', 'average', 'bayesaverage', 'Board Game Rank', 'Strategy Game Rank', 'Family Game Rank', 'stddev', 'median', 'owned', 'trading', 'wanting', 'wishing', 'numcomments', 'numweights', 'averageweight', 'boardgameintegration', 'boardgamecompilation', 'Party Game Rank', 'Abstract Game Rank', 'Thematic Rank', 'War Game Rank', 'Customizable Rank', "Children's Game Rank", 'RPG Item Rank', 'Accessory Rank', 'Video Game Rank', 'Amiga Rank', 'Commodore 64 Rank', 'Arcade Rank', 'Atari ST Rank']

,Unnamed: 0,type,id,thumbnail,image,primary,alternate,description,yearpublished,minplayers,...,War Game Rank,Customizable Rank,Children's Game Rank,RPG Item Rank,Accessory Rank,Video Game Rank,Amiga Rank,Commodore 64 Rank,Arcade Rank,Atari ST Rank
0,0,boardgame,30549,https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXL...,https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXL...,Pandemic,"['EPIZOotic', 'Pandemia', 'Pandemia 10 Anivers...","In Pandemic, several virulent diseases have br...",2008,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,boardgame,822,https://cf.geekdo-images.com/okM0dq_bEXnbyQTOv...,https://cf.geekdo-images.com/okM0dq_bEXnbyQTOv...,Carcassonne,"['Carcassonne Jubilee Edition', 'Carcassonne: ...",Carcassonne is a tile-placement game in which ...,2000,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,boardgame,13,https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ...,https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ...,Catan,"['CATAN', 'Catan (Колонизаторы)', 'Catan telep...","In CATAN (formerly The Settlers of Catan), pla...",1995,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

=== Preview: mechanics.csv ===
['BGGId', 'Alliances', 'Area Majority / Influence', 'Auction/Bidding', 'Dice Rolling', 'Hand Management', 'Simultaneous Action Selection', 'Trick-taking', 'Hexagon Grid', 'Once-Per-Game Abilities', 'Set Collection', 'Tile Placement', 'Action Points', 'Investment', 'Market', 'Square Grid', 'Stock Holding', 'Victory Points as a Resource', 'Enclosure', 'Pattern Building', 'Pattern Recognition', 'Modular Board', 'Network and Route Building', 'Point to Point Movement', 'Melding and Splaying', 'Negotiation', 'Trading', 'Push Your Luck', 'Income', 'Race', 'Random Production', 'Variable Set-up', 'Roll / Spin and Move', 'Variable Player Powers', 'Action Queue', 'Bias', 'Grid Movement', 'Lose a Turn', 'Programmed Movement', 'Scenario / Mission / Campaign Game', 'Voting', 'Events', 'Paper-and-Pencil', 'Player Elimination', 'Role Playing', 'Movement Points', 'Simulation', 'Variable Phase Order', 'Area Movement', 'Commodity Speculation', 'Cooperative Game', 'Deduction', 'Sudden Death Ending', 'Connections', 'Highest-Lowest Scoring', 'Betting and Bluffing', 'Memory', 'Score-and-Reset Game', 'Layering', 'Map Addition', 'Secret Unit Deployment', 'Increase Value of Unchosen Resources', 'Ratio / Combat Results Table', 'Take That', 'Team-Based Game', 'Campaign / Battle Card Driven', 'Tech Trees / Tech Tracks', 'Player Judge', 'Chit-Pull System', 'Three Dimensional Movement', 'Action Drafting', 'Minimap Resolution', 'Stat Check Resolution', 'Action Timer', 'Pick-up and Deliver', 'Map Deformation', 'Bingo', 'Crayon Rail System', 'Multiple Maps', 'Hidden Roles', 'Line Drawing', 'Tug of War', 'Pattern Movement', 'Static Capture', 'Different Dice Movement', 'Chaining', 'Ladder Climbing', 'Predictive Bid', 'Solo / Solitaire Game', 'Line of Sight', 'Critical Hits and Failures', 'Interrupts', 'Zone of Control', 'Bribery', 'End Game Bonuses', 'Area-Impulse', 'Worker Placement', 'Measurement Movement', 'Map Reduction', 'Real-Time', 'Resource to Move', 'Mancala', 'Ownership', 'Kill Steal', 'Hidden Movement', 'Track Movement', 'Deck Construction', 'Drafting', 'TableauBuilding', "Prisoner's Dilemma", 'Hidden Victory Points', 'Movement Template', 'Slide/Push', 'Targeted Clues', 'Command Cards', 'Grid Coverage', 'Relative Movement', 'Action/Event', 'Card Play Conflict Resolution', 'I Cut, You Choose', 'Die Icon Resolution', 'Elapsed Real Time Ending', 'Advantage Token', 'Storytelling', 'Catch the Leader', 'Roles with Asymmetric Information', 'Traitor Game', 'Moving Multiple Units', 'Semi-Cooperative Game', 'Communication Limits', 'Time Track', 'Speed Matching', 'Cube Tower', 'Re-rolling and Locking', 'Impulse Movement', 'Loans', 'Delayed Purchase', 'Deck, Bag, and Pool Building', 'Move Through Deck', 'Single Loser Game', 'Matching', 'Induction', 'Physical Removal', 'Narrative Choice / Paragraph', 'Pieces as Map', 'Follow', 'Finale Ending', 'Order Counters', 'Contracts', 'Passed Action Token', 'King of the Hill', 'Action Retrieval', 'Force Commitment', 'Rondel', 'Automatic Resource Growth', 'Legacy Game', 'Dexterity', 'Physical']

,BGGId,Alliances,Area Majority / Influence,Auction/Bidding,Dice Rolling,Hand Management,Simultaneous Action Selection,Trick-taking,Hexagon Grid,Once-Per-Game Abilities,...,Contracts,Passed Action Token,King of the Hill,Action Retrieval,Force Commitment,Rondel,Automatic Resource Growth,Legacy Game,Dexterity,Physical
0,1,1,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,1,0,0,1,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

=== Preview: themes.csv ===
['BGGId', 'Adventure', 'Fantasy', 'Fighting', 'Environmental', 'Medical', 'Economic', 'Industry / Manufacturing', 'Transportation', 'Science Fiction', 'Space Exploration', 'Civilization', 'Civil War', 'Movies / TV / Radio theme', 'Novel-based', 'Age of Reason', 'Mythology', 'Renaissance', 'American West', 'Animals', 'Modern Warfare', 'Medieval', 'Ancient', 'Nautical', 'Post-Napoleonic', 'Horror', 'Farming', 'Religious', 'Travel', 'Murder/Mystery', 'Pirates', 'Comic Book / Strip', 'Mature / Adult', 'Video Game Theme', 'Spies/Secret Agents', 'Arabian', 'Prehistoric', 'Trains', 'Aviation / Flight', 'Zombies', 'World War II', 'Racing', 'Pike and Shot', 'World War I', 'Humor', 'Sports', 'Mafia', 'American Indian Wars', 'Napoleonic', 'American Revolutionary War', 'Vietnam War', 'American Civil War', 'Number', 'Trivia', 'Music', 'Korean War', 'City Building', 'Political', 'Math', 'Maze', 'Theme_Food / Cooking', 'Theme_Superheroes', 'Theme_Anime / Manga', 'Theme_Cthulhu Mythos', 'Theme_Alternate History', 'Theme_Anthropomorphic Animals', 'Theme_Vikings', 'Theme_Post-Apocalyptic', 'Theme_Time Travel', 'Theme_Colonial', 'Theme_Mystery / Cri', 'Theme_Robots', 'Theme_Retro', 'Theme_Mad Science / Mad Scientist', 'Theme_Mining', 'Theme_Art', 'Theme_Archaeology / Paleontology', 'Theme_Witches', 'Theme_Deserts', 'Theme_Tropical', 'Theme_Steampunk', 'Theme_Gardening', 'Theme_Sieg', 'Theme_Flowers', 'Theme_Natur', 'Theme_Native Americans / First Peoples', 'Theme_Circus', 'Theme_Ninjas', 'Theme_King Arthur / The Knights of the Round Table / Camelot', 'Theme_Cyberpunk', 'Theme_Submarines', 'Theme_Construction', 'Theme_Samurai', 'Theme_Fantasy Sports', 'Theme_Love / Romanc', 'Theme_Biology', 'Theme_Kaiju', 'Theme_Gladiators', 'Theme_City', 'Theme_Villainy', 'Theme_Weather', 'Theme_Amusement Parks / Theme Parks', 'Theme_Airships / Blimps / Dirigibles / Zeppelins', 'Theme_Spooky Old Houses', 'Theme_Mech Warfar', 'Theme_Polic', 'Theme_Books / Libraries', 'Theme_Alchemy', 'Theme_Tropical Islands', 'Theme_Boardgaming', 'Theme_Oil / Gas / Petroleu', 'Theme_Arcade Video Games', 'Theme_Safaris', 'Theme_Dreams / Nightmares', 'Theme_Evolution', 'Theme_Survival', 'Theme_Fruit', 'Theme_Jail / Prison (Modern)', 'Theme_Movie Industry', 'Theme_Animal Battles', 'Theme_Firefighting', 'Theme_Video Game Theme: Nintendo', 'Theme_Climate Chang', 'Theme_Helicopters', 'Theme_Psychology', 'Theme_Sci-Fi Sports', 'Theme_Sewing / Knitting / Cloth-Making', 'Theme_Beaches', 'Theme_Under the Sea', 'Theme_Aztecs', 'Theme_Trees and Forests', 'Theme_Mayans', 'Theme_Chibis', 'Theme_US National Parks', 'Theme_Scienc', 'Theme_Chemistry', 'Theme_Volcanoes', 'Theme_Fictional Games', 'Theme_Druids', 'Theme_Music Making & Makers', 'Theme_Psychic Powers', 'Theme_Trash / Garbag', 'Theme_Silk Road', 'Theme_Cereal Games', 'Theme_Automotive Industry', 'Theme_Video Game Theme: Tetris', 'Theme_TV Detectives', 'Theme_Romance of the Three Kingdoms', 'Theme_Trucks', 'Theme_Hanseatic Leagu', 'Theme_Chivalry / Jousting / Tournaments (Medieval Europe)', 'Theme_Cannibals / Cannibalis', 'Theme_Canals', 'Theme_My Best Lif', 'Theme_Nuclear option', 'Theme_Astronomy', 'Theme_Cemeteries / Graveyards', 'Theme_Movies', 'Theme_Hackers', 'Theme_Pub, Bars, Bistros...', 'Theme_Jewelry', 'Theme_School / College / University', 'Theme_UFOs', 'Theme_Templ', 'Theme_Mail / Stamps / The Post Offic', 'Theme_Memes', 'Theme_Computer / Information Technology Industry', 'Theme_Attorneys / Courts', 'Theme_Hot Air Balloons', 'Theme_Journalis', 'Theme_Motorcycles', "Theme_Rubik's Cub", 'Theme_Dolls', 'Theme_Traffic / Driving', 'Theme_FIFA World Cup', 'Theme_Video Game Theme: Pokémon', 'Theme_Floating islands in the sky', 'Theme_Dieselpunk', 'Theme_Disney Theme Parks', 'Theme_Video Game Theme: Resident Evil', 'Theme_Video Game Theme: SEGA', 'Theme_Teaching Programming', 'Theme_Battle Royal', 'Theme_Earthquakes', 'Theme_Bacteria', 'Theme_Painting / Paintings', 'Theme_Television (TV) Industry', 'Theme_Knights Templar', 'Theme_African Americans', 'Theme_Hell', 'Theme_Tiki Cultur', 'Theme_Astrology', 'Theme_Video Game Theme: The Oregon Trail', 'Theme_Māori', 'Theme_Video Game Theme: Super Mario Bros.', 'Theme_Mushrooms', 'Theme_Pulp', 'Theme_Video Game Theme: Minecraft', 'Theme_Video Game Theme: Final Fantasy', 'Theme_Video Game Theme: Carmen Sandiego', 'Theme_Care Bears', 'Theme_Hike-Hiking', 'Theme_Inuit Peoples', 'Theme_Perfu', 'Theme_Camping', 'Theme_Latin American Political Games', 'Theme_Spanish Political Games', 'Theme_Video Game Theme: Doo', 'Theme_Fashion', 'Theme_Geocaching', 'Theme_Ecology', 'Theme_Chernobyl', 'Theme_Photography', 'Theme_French Foreign Legion', 'Theme_Cruise ships', 'Theme_Apache Tribes', 'Theme_Rivers', 'Theme_Flags identification']

,BGGId,Adventure,Fantasy,Fighting,Environmental,Medical,Economic,Industry / Manufacturing,Transportation,Science Fiction,...,Theme_Fashion,Theme_Geocaching,Theme_Ecology,Theme_Chernobyl,Theme_Photography,Theme_French Foreign Legion,Theme_Cruise ships,Theme_Apache Tribes,Theme_Rivers,Theme_Flags identification
0,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

=== Preview: subcategories.csv ===
['BGGId', 'Exploration', 'Miniatures', 'Territory Building', 'Card Game', 'Educational', 'Puzzle', 'Collectible Components', 'Word Game', 'Print & Play', 'Electronic']

,BGGId,Exploration,Miniatures,Territory Building,Card Game,Educational,Puzzle,Collectible Components,Word Game,Print & Play,Electronic
0,1,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,1,0,0,0,0,0,0
2,3,0,0,0,0,0,0,0,0,0,0

In [3]:
file_list = [
    "large_bgg-26m-reviews.csv",
    "large_games_detailed_info2025.csv",
    "games.csv",
    "games_detailed_info.csv",
    "mechanics.csv",
    "themes.csv",
    "subcategories.csv"
]

for f in file_list:
    path = f"../Dataset/Raw/{f}"
    try:
        df = pd.read_csv(path)
        print(f"{f}: {df.shape}")
    except Exception as e:
        print(f"Error reading {f}: {e}")

large_bgg-26m-reviews.csv: (26200012, 6)
large_games_detailed_info2025.csv: (27780, 52)
games.csv: (21925, 48)

C:\Users\felix\AppData\Local\Temp\ipykernel_19416\661793934.py:14: DtypeWarning: Columns (29,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

games_detailed_info.csv: (21631, 56)
mechanics.csv: (21925, 158)
themes.csv: (21925, 218)
subcategories.csv: (21925, 11)