In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

RAW_DIR = Path("../Dataset/Raw")
PROCESSED_DIR = Path("../Dataset/Processed")

PROCESSED_DIR.mkdir(exist_ok=True)

In [2]:
meta_path = RAW_DIR / "games_detailed_info.csv"
df_meta = pd.read_csv(meta_path)

print(df_meta.shape)
df_meta.head()

(21631, 56)

C:\Users\felix\AppData\Local\Temp\ipykernel_6680\448021550.py:2: DtypeWarning: Columns (29,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df_meta = pd.read_csv(meta_path)

,Unnamed: 0,type,id,thumbnail,image,primary,alternate,description,yearpublished,minplayers,...,War Game Rank,Customizable Rank,Children's Game Rank,RPG Item Rank,Accessory Rank,Video Game Rank,Amiga Rank,Commodore 64 Rank,Arcade Rank,Atari ST Rank
0,0,boardgame,30549,https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXL...,https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXL...,Pandemic,"['EPIZOotic', 'Pandemia', 'Pandemia 10 Anivers...","In Pandemic, several virulent diseases have br...",2008,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,boardgame,822,https://cf.geekdo-images.com/okM0dq_bEXnbyQTOv...,https://cf.geekdo-images.com/okM0dq_bEXnbyQTOv...,Carcassonne,"['Carcassonne Jubilee Edition', 'Carcassonne: ...",Carcassonne is a tile-placement game in which ...,2000,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,boardgame,13,https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ...,https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ...,Catan,"['CATAN', 'Catan (Колонизаторы)', 'Catan telep...","In CATAN (formerly The Settlers of Catan), pla...",1995,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,boardgame,68448,https://cf.geekdo-images.com/RvFVTEpnbb4NM7k0I...,https://cf.geekdo-images.com/RvFVTEpnbb4NM7k0I...,7 Wonders,"['7 csoda', '7 Cudów Świata', '7 divů světa', ...",You are the leader of one of the 7 great citie...,2010,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,boardgame,36218,https://cf.geekdo-images.com/j6iQpZ4XkemZP07HN...,https://cf.geekdo-images.com/j6iQpZ4XkemZP07HN...,Dominion,"['Dominion: Basisspiel', 'Dominion: In naam va...","&quot;You are a monarch, like your parents bef...",2008,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
meta_cols = [
    "id", "primary", "yearpublished", "minplayers", "maxplayers", "minplaytime",
    "maxplaytime", "minage", "Board Game Rank", "average", "bayesaverage", 
    "usersrated", "averageweight", "boardgamecategory", 
    "boardgamemechanic", "description"
]

df_meta_clean = df_meta[meta_cols].drop_duplicates(subset="id")

df_meta_clean = df_meta_clean.rename(columns={
    "primary": "name",
    "Board Game Rank": "rank",
    "boardgamecategory": "category",
    "boardgamemechanic": "mechanic"
})

df_meta_clean.head()

,id,name,yearpublished,minplayers,maxplayers,minplaytime,maxplaytime,minage,rank,average,bayesaverage,usersrated,averageweight,category,mechanic,description
0,30549,Pandemic,2008,2,4,45,45,8,106,7.58896,7.48669,109006,2.4063,['Medical'],"['Action Points', 'Cooperative Game', 'Hand Ma...","In Pandemic, several virulent diseases have br..."
1,822,Carcassonne,2000,2,5,30,45,7,191,7.41837,7.30857,108776,1.9057,"['City Building', 'Medieval', 'Territory Build...","['Area Majority / Influence', 'Map Addition', ...",Carcassonne is a tile-placement game in which ...
2,13,Catan,1995,3,4,60,120,10,429,7.13598,6.96965,108064,2.3130,"['Economic', 'Negotiation']","['Dice Rolling', 'Hexagon Grid', 'Income', 'Mo...","In CATAN (formerly The Settlers of Catan), pla..."
3,68448,7 Wonders,2010,2,7,30,30,10,73,7.73515,7.63355,90021,2.3264,"['Ancient', 'Card Game', 'City Building', 'Civ...","['Drafting', 'Hand Management', 'Set Collectio...",You are the leader of one of the 7 great citie...
4,36218,Dominion,2008,2,4,30,30,13,104,7.61000,7.49912,81582,2.3542,"['Card Game', 'Medieval']","['Deck, Bag, and Pool Building', 'Delayed Purc...","&quot;You are a monarch, like your parents bef..."

In [4]:
reviews_path = RAW_DIR / "large_bgg-26m-reviews.csv"

df_reviews = pd.read_csv(
    reviews_path,
    usecols=["user", "ID", "rating", "comment", "name"],
    nrows=500000
)

print(df_reviews.shape)
df_reviews.head()

(500000, 5)

,user,rating,comment,ID,name
0,sidehacker,10.0,NaN,13,CATAN
1,Varthlokkur,10.0,NaN,13,CATAN
2,dougthonus,10.0,"Currently, this sits on my list as my favorite...",13,CATAN
3,cypar7,10.0,"I know it says how many plays, but many, many ...",13,CATAN
4,ssmooth,10.0,NaN,13,CATAN

In [5]:
df_reviews = df_reviews.dropna(subset=["comment"])
df_reviews["comment"] = df_reviews["comment"].astype(str)

df_reviews_clean = df_reviews[df_reviews["comment"].str.strip() != ""]
df_reviews_clean.head()

,user,rating,comment,ID,name
2,dougthonus,10.0,"Currently, this sits on my list as my favorite...",13,CATAN
3,cypar7,10.0,"I know it says how many plays, but many, many ...",13,CATAN
7,hreimer,10.0,i will never tire of this game.. Awesome,13,CATAN
11,daredevil,10.0,This is probably the best game I ever played. ...,13,CATAN
16,hurkle,10.0,Fantastic game. Got me hooked on games all ove...,13,CATAN

In [6]:
df_merged = df_reviews_clean.merge(
    df_meta_clean,
    left_on="ID",
    right_on="id",
    how="left"
)

df_merged.head()

NameError: name 'df_meta_clean' is not defined

In [ ]:
output_path = PROCESSED_DIR / "merged_clean_sample.csv"
df_merged.to_csv(output_path, index=False)

print("Saved to:", output_path)